name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  arch-test:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install deps
        run: |
          pacman -Sy --noconfirm base-devel cmake gcc

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build test
        run: |
          cmake -B build -D ARGVX_BUILD_TEST=ON
          cmake --build build

      - name: Run test
        run: |
          set +e
          ./build/argvx-test
          if [ $? -ne 0 ]; then
            echo "test exited with non-zero code ($?)"
            exit 1
          fi
